# Use the official Node.js 14 image as a parent image
FROM node:14

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install --only=production

# Copy the rest of your application's source code from your host to your image filesystem.
COPY . .

# Inform Docker that the container listens on the specified network ports at runtime.
EXPOSE 3000

# Command to run your app
CMD ["node", "server.js"]